# Run pytest against an actual FirecREST server,
# rather than just a mock server.

name: Server

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:  # TODO delete

jobs:

  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
        firecrest-version: ["v1.13.0"]

    # services:
    #  rabbitmq:
    #     image: rabbitmq:3.8.14-management
    #     ports:
    #       - 5672:5672
    #       - 15672:15672

    steps:
    - uses: actions/checkout@v3

    - name: checkout the firecrest repository
      uses: actions/checkout@v3
      with:
        repository: eth-cscs/firecrest
        ref: ${{ matrix.firecrest-version }}
        path: .demo-server

    - name: Ensure permissions of SSH Keys
      run: |
        chmod 400 .demo-server/deploy/test-build/environment/keys/ca-key
        chmod 400 .demo-server/deploy/test-build/environment/keys/user-key

    - name: Build the FirecREST images
      run: |
        docker-compose build f7t-base
      working-directory: .demo-server/deploy/demo

    - name: check existing images
      run: docker image list --all

    # - name: Build and start the FirecREST server
    #   run: docker-compose up --build --detach
    #   working-directory: .demo-server/deploy/demo

    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: ${{ matrix.python-version }}
    #     cache: 'pip'
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -e .[dev]
    # - name: Test with pytest
    #   run: pytest -vv --cov=aiida_firecrest
